// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package microservice

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "microservice", Method: "PUT", Endpoint: "/api/v1/projects/microservices/{projectId}/canvas", Command: []string{"microservice", "apply"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "DELETE", Endpoint: "/api/v1/projects/microservices/{projectId}", Command: []string{"microservice", "delete"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "POST", Endpoint: "/api/v1/projects/microservices", Command: []string{"microservice", "deploy"}, Args: []string(nil), Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "POST", Endpoint: "/api/v1/projects/microservices/detect", Command: []string{"microservice", "detect"}, Args: []string(nil), Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "PATCH", Endpoint: "/api/v1/projects/microservices/{projectId}/domains", Command: []string{"microservice", "domains", "update"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "DELETE", Endpoint: "/api/v1/projects/microservices/{projectId}/services/{serviceId}/environment", Command: []string{"microservice", "env", "clear"}, Args: []string{"project-id", "service-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "GET", Endpoint: "/api/v1/projects/microservices/{projectId}/services/{serviceId}/environment", Command: []string{"microservice", "env", "get"}, Args: []string{"project-id", "service-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "POST", Endpoint: "/api/v1/projects/microservices/{projectId}/services/{serviceId}/environment/import", Command: []string{"microservice", "env", "import"}, Args: []string{"project-id", "service-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "PUT", Endpoint: "/api/v1/projects/microservices/{projectId}/services/{serviceId}/environment", Command: []string{"microservice", "env", "set"}, Args: []string{"project-id", "service-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "GET", Endpoint: "/api/v1/projects/microservices/{projectId}", Command: []string{"microservice", "get"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "DELETE", Endpoint: "/api/v1/projects/microservices/{projectId}/history/{snapshotId}", Command: []string{"microservice", "history", "delete"}, Args: []string{"project-id", "snapshot-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "GET", Endpoint: "/api/v1/projects/microservices/{projectId}/history", Command: []string{"microservice", "history", "list"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "GET", Endpoint: "/api/v1/projects/microservices/{projectId}/runtime-pods", Command: []string{"microservice", "pods"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "GET", Endpoint: "/api/v1/projects/microservices/{projectId}/readiness", Command: []string{"microservice", "readiness"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "POST", Endpoint: "/api/v1/projects/microservices/{projectId}/redeploy", Command: []string{"microservice", "redeploy"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "POST", Endpoint: "/api/v1/projects/microservices/{projectId}/rollback", Command: []string{"microservice", "rollback"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "GET", Endpoint: "/api/v1/projects/microservices/{projectId}/webhook", Command: []string{"microservice", "webhook", "get"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
	{Feature: "microservice", Method: "POST", Endpoint: "/api/v1/projects/microservices/{projectId}/webhook", Command: []string{"microservice", "webhook", "update"}, Args: []string{"project-id"}, Controller: "MicroserviceProjectController"},
}
