apiVersion: cli.a8s.io/v1alpha1
kind: Config

currentContext: development

preferences:
  output: table
  color: auto
  timeout: 30s
  requestTimeout: 20s
  pollingInterval: 3s

contexts:
  development:
    server: http://localhost:8080
    namespace: ns-local
    targetCluster: local
    tls:
      insecureSkipVerify: false
      caFile: ""
    auth:
      issuer: https://keycloak.autonomous-istad.com/realms/a8s
      clientId: a8s-cli
      credentialKey: context:development
