// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package profile

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "profile", Method: "POST", Endpoint: "/api/v1/profile/me/deactivate", Command: []string{"profile", "account", "deactivate"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "DELETE", Endpoint: "/api/v1/profile/me", Command: []string{"profile", "account", "delete"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "POST", Endpoint: "/api/v1/profile/me/reactivate", Command: []string{"profile", "account", "reactivate"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "GET", Endpoint: "/api/v1/profile/me/account-status", Command: []string{"profile", "account", "status"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "DELETE", Endpoint: "/api/v1/profile/me/avatar", Command: []string{"profile", "avatar", "delete"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "GET", Endpoint: "/api/v1/profile/me/avatar", Command: []string{"profile", "avatar", "download"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "POST", Endpoint: "/api/v1/profile/me/avatar", Command: []string{"profile", "avatar", "upload"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "GET", Endpoint: "/api/v1/profile/me", Command: []string{"profile", "get"}, Args: []string(nil), Controller: "ProfileController"},
	{Feature: "profile", Method: "PATCH", Endpoint: "/api/v1/profile/me", Command: []string{"profile", "update"}, Args: []string(nil), Controller: "ProfileController"},
}
