// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package auth

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "auth", Method: "POST", Endpoint: "/api/v1/auth/session/onboarding", Command: []string{"auth", "onboarding", "start"}, Args: []string(nil), Controller: "AuthController"},
	{Feature: "auth", Method: "GET", Endpoint: "/api/v1/auth/session/onboarding", Command: []string{"auth", "onboarding", "status"}, Args: []string(nil), Controller: "AuthController"},
	{Feature: "auth", Method: "POST", Endpoint: "/api/v1/auth/keycloak/users/{keycloakUserId}/verify-email", Command: []string{"auth", "verify-email", "start"}, Args: []string{"keycloak-user-id"}, Controller: "AuthController"},
	{Feature: "auth", Method: "GET", Endpoint: "/api/v1/auth/keycloak/users/{keycloakUserId}/verify-email", Command: []string{"auth", "verify-email", "status"}, Args: []string{"keycloak-user-id"}, Controller: "AuthController"},
}
