// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package testingkit

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "testingkit", Method: "DELETE", Endpoint: "/api/v1/projects/live/{projectId}/benchmark/runs/{runId}", Command: []string{"benchmark", "delete"}, Args: []string{"project-id", "run-id"}, Controller: "BenchmarkController"},
	{Feature: "testingkit", Method: "GET", Endpoint: "/api/v1/projects/live/{projectId}/benchmark/runs/{runId}", Command: []string{"benchmark", "get"}, Args: []string{"project-id", "run-id"}, Controller: "BenchmarkController"},
	{Feature: "testingkit", Method: "GET", Endpoint: "/api/v1/projects/live/{projectId}/benchmark/runs", Command: []string{"benchmark", "list"}, Args: []string{"project-id"}, Controller: "BenchmarkController"},
	{Feature: "testingkit", Method: "POST", Endpoint: "/api/v1/projects/live/{projectId}/benchmark/run", Command: []string{"benchmark", "run"}, Args: []string{"project-id"}, Controller: "BenchmarkController"},
}
