// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package singledb

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/clone-from-backup", Command: []string{"database", "clone-from-backup"}, Args: []string(nil), Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/console/data", Command: []string{"database", "console", "data"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/console/namespaces", Command: []string{"database", "console", "namespaces"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/console/objects", Command: []string{"database", "console", "objects"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/console/query", Command: []string{"database", "console", "query"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/console/test", Command: []string{"database", "console", "test"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/credentials", Command: []string{"database", "credentials"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "DELETE", Endpoint: "/api/v1/database-deployments/{deploymentId}", Command: []string{"database", "delete"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments", Command: []string{"database", "deploy"}, Args: []string(nil), Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}", Command: []string{"database", "get"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments", Command: []string{"database", "list"}, Args: []string(nil), Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/metrics", Command: []string{"database", "metrics"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/restart", Command: []string{"database", "restart"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/rotate-password", Command: []string{"database", "rotate-password"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "PATCH", Endpoint: "/api/v1/database-deployments/{deploymentId}/settings", Command: []string{"database", "settings", "update"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "PATCH", Endpoint: "/api/v1/database-deployments/{deploymentId}", Command: []string{"database", "update"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/upgrade-version", Command: []string{"database", "upgrade"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
	{Feature: "singledb", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/verify-password", Command: []string{"database", "verify-password"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentController"},
}
