// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package entitlements

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "entitlements", Method: "GET", Endpoint: "/api/v1/workspaces/entitlements", Command: []string{"workspace", "entitlements"}, Args: []string(nil), Controller: "WorkspaceEntitlementController"},
}
