// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package notifications

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "notifications", Method: "GET", Endpoint: "/api/notifications/history/{userId}", Command: []string{"notification", "list"}, Args: []string{"user-id"}, Controller: "NotificationController"},
	{Feature: "notifications", Method: "GET", Endpoint: "/api/notifications/preferences/{userId}", Command: []string{"notification", "preferences", "get"}, Args: []string{"user-id"}, Controller: "NotificationController"},
	{Feature: "notifications", Method: "POST", Endpoint: "/api/notifications/preferences/{userId}", Command: []string{"notification", "preferences", "set"}, Args: []string{"user-id"}, Controller: "NotificationController"},
	{Feature: "notifications", Method: "POST", Endpoint: "/api/notifications/{notificationId}/read", Command: []string{"notification", "read"}, Args: []string{"notification-id"}, Controller: "NotificationController"},
}
