package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var row = regexp.MustCompile(`^\| ` + "`" + `(GET|POST|PUT|PATCH|DELETE)` + "`" + ` \| ` + "`" + `([^` + "`" + `]+)` + "`" + ` \| ` + "`" + `(a8s [^` + "`" + `]+)` + "`" + ` \| ` + "`" + `([^` + "`" + `]+)` + "`" + ` \|$`)
var placeholder = regexp.MustCompile(`^<([^>]+)>$`)
var pathVariable = regexp.MustCompile(`\{([^}]+)\}`)
var backendFeatures = []string{
	"admin", "alerts", "auth", "databasebackup", "databaseconsole", "dbcluster",
	"documentation", "entitlements", "gitintegration", "imagescanner", "microservice",
	"monitoring", "monolithic", "notifications", "payments", "profile", "projects",
	"singledb", "sonarqube", "testingkit", "workspaces",
}

type route struct {
	feature, method, endpoint, controller string
	command, args                         []string
}

func main() {
	input := filepath.FromSlash("docs/backend-api-cli-catalog.md")
	output := filepath.FromSlash("internal/cli/catalog/generated_routes.go")
	file, err := os.Open(input)
	must(err)
	defer file.Close()

	seen := map[string]bool{}
	var routes []route
	feature := ""
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "## ") {
			feature = strings.TrimSpace(strings.TrimPrefix(line, "## "))
		}
		match := row.FindStringSubmatch(line)
		if match == nil {
			continue
		}
		words := strings.Fields(strings.TrimPrefix(match[3], "a8s "))
		var command, args []string
		for _, word := range words {
			if strings.HasPrefix(word, "--") {
				break
			}
			if value := placeholder.FindStringSubmatch(word); value != nil {
				args = append(args, value[1])
				continue
			}
			command = append(command, word)
		}
		var variables []string
		for _, value := range pathVariable.FindAllStringSubmatch(match[2], -1) {
			name := kebab(value[1])
			if value[1] != "namespace" || contains(args, "namespace") {
				variables = append(variables, name)
			}
		}
		for len(args) < len(variables) {
			args = append(args, variables[len(args)])
		}
		key := strings.Join(append(append([]string{}, command...), args...), " ")
		if seen[key] {
			continue
		}
		seen[key] = true
		routes = append(routes, route{feature, match[1], match[2], match[4], command, args})
	}
	must(scanner.Err())
	sort.Slice(routes, func(i, j int) bool {
		return strings.Join(routes[i].command, " ") < strings.Join(routes[j].command, " ")
	})

	var out strings.Builder
	out.WriteString("// Code generated by scripts/generate-route-registry; DO NOT EDIT.\n\n")
	out.WriteString("package catalog\n\n")
	out.WriteString("var Routes = []Route{\n")
	for _, route := range routes {
		fmt.Fprintf(&out, "\t{Feature: %q, Method: %q, Endpoint: %q, Command: %#v, Args: %#v, Controller: %q},\n",
			route.feature, route.method, route.endpoint, route.command, route.args, route.controller)
	}
	out.WriteString("}\n")
	must(os.WriteFile(output, []byte(out.String()), 0o644))
	writeFeatureRoutes(routes)
}

func writeFeatureRoutes(routes []route) {
	grouped := map[string][]route{}
	for _, value := range routes {
		grouped[value.feature] = append(grouped[value.feature], value)
	}
	for _, feature := range backendFeatures {
		values := grouped[feature]
		packageName := feature
		if feature == "documentation" {
			packageName = "documentationfeature"
		}
		var out strings.Builder
		out.WriteString("// Code generated by scripts/generate-route-registry; DO NOT EDIT.\n\n")
		fmt.Fprintf(&out, "package %s\n\n", packageName)
		out.WriteString("import \"github.com/yourname/a8s/internal/cli/catalog\"\n\n")
		out.WriteString("var Routes = []catalog.Route{\n")
		for _, value := range values {
			fmt.Fprintf(&out, "\t{Feature: %q, Method: %q, Endpoint: %q, Command: %#v, Args: %#v, Controller: %q},\n",
				value.feature, value.method, value.endpoint, value.command, value.args, value.controller)
		}
		out.WriteString("}\n")
		path := filepath.Join("internal", "cli", "features", feature, "routes_gen.go")
		must(os.WriteFile(path, []byte(out.String()), 0o644))
	}
}

func contains(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

func kebab(value string) string {
	var result strings.Builder
	for index, char := range value {
		if index > 0 && char >= 'A' && char <= 'Z' {
			result.WriteByte('-')
		}
		result.WriteRune(char)
	}
	return strings.ToLower(result.String())
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
