// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package monolithic

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "monolithic", Method: "PATCH", Endpoint: "/api/v1/projects/{projectId}/auto-deploy", Command: []string{"project", "auto-deploy", "set"}, Args: []string{"project-id"}, Controller: "ProjectWebhookController"},
	{Feature: "monolithic", Method: "GET", Endpoint: "/api/v1/projects/{projectId}/branches", Command: []string{"project", "branches"}, Args: []string{"project-id"}, Controller: "ProjectWebhookController"},
	{Feature: "monolithic", Method: "DELETE", Endpoint: "/api/v1/projects/{projectId}", Command: []string{"project", "delete"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects", Command: []string{"project", "deploy"}, Args: []string(nil), Controller: "ProjectController"},
	{Feature: "monolithic", Method: "PATCH", Endpoint: "/api/v1/projects/{projectId}/domain", Command: []string{"project", "domain", "set"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/domain/sync", Command: []string{"project", "domain", "sync"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "GET", Endpoint: "/api/v1/projects/{projectId}/environment", Command: []string{"project", "env", "get"}, Args: []string{"project-id"}, Controller: "ProjectEnvironmentController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/environment/import", Command: []string{"project", "env", "import"}, Args: []string{"project-id"}, Controller: "ProjectEnvironmentController"},
	{Feature: "monolithic", Method: "PUT", Endpoint: "/api/v1/projects/{projectId}/environment", Command: []string{"project", "env", "set"}, Args: []string{"project-id"}, Controller: "ProjectEnvironmentController"},
	{Feature: "monolithic", Method: "GET", Endpoint: "/api/v1/projects/{projectId}", Command: []string{"project", "get"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "GET", Endpoint: "/api/v1/projects", Command: []string{"project", "list"}, Args: []string(nil), Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/sync", Command: []string{"project", "redeploy"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "DELETE", Endpoint: "/api/v1/projects/{projectId}/releases/{releaseId}", Command: []string{"project", "release", "delete"}, Args: []string{"project-id", "release-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/releases/{releaseId}/rollback", Command: []string{"project", "release", "rollback"}, Args: []string{"project-id", "release-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "GET", Endpoint: "/api/v1/projects/{projectId}/releases", Command: []string{"project", "releases"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/repository/connect", Command: []string{"project", "repository", "connect"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/rollback", Command: []string{"project", "rollback"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "PATCH", Endpoint: "/api/v1/projects/{projectId}/settings", Command: []string{"project", "settings", "update"}, Args: []string{"project-id"}, Controller: "ProjectController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/webhook", Command: []string{"project", "webhook", "create"}, Args: []string{"project-id"}, Controller: "ProjectWebhookController"},
	{Feature: "monolithic", Method: "DELETE", Endpoint: "/api/v1/projects/{projectId}/webhook", Command: []string{"project", "webhook", "delete"}, Args: []string{"project-id"}, Controller: "ProjectWebhookController"},
	{Feature: "monolithic", Method: "GET", Endpoint: "/api/v1/projects/{projectId}/webhook", Command: []string{"project", "webhook", "get"}, Args: []string{"project-id"}, Controller: "ProjectWebhookController"},
	{Feature: "monolithic", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/webhook/rotate", Command: []string{"project", "webhook", "rotate"}, Args: []string{"project-id"}, Controller: "ProjectWebhookController"},
}
