// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package monitoring

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "monitoring", Method: "GET", Endpoint: "/api/v1/monitoring/overview", Command: []string{"monitoring", "overview"}, Args: []string(nil), Controller: "MonitoringController"},
}
