// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package projects

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "projects", Method: "GET", Endpoint: "/api/v1/projects/{projectId}/defectdojo", Command: []string{"defectdojo", "access"}, Args: []string{"project-id"}, Controller: "ProjectDefectDojoController"},
	{Feature: "projects", Method: "PUT", Endpoint: "/api/v1/projects/{projectId}/defectdojo/token", Command: []string{"defectdojo", "token", "sync"}, Args: []string{"project-id"}, Controller: "ProjectDefectDojoController"},
	{Feature: "projects", Method: "GET", Endpoint: "/api/v1/projects/live", Command: []string{"project", "live", "list"}, Args: []string(nil), Controller: "LiveProjectController"},
	{Feature: "projects", Method: "GET", Endpoint: "/api/v1/jenkins/logs/stream", Command: []string{"project", "logs"}, Args: []string(nil), Controller: "JenkinsController"},
}
