// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package documentationfeature

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "documentation", Method: "DELETE", Endpoint: "/api/admin/documentation/content", Command: []string{"admin", "docs", "delete"}, Args: []string(nil), Controller: "DocumentationController"},
	{Feature: "documentation", Method: "GET", Endpoint: "/api/admin/documentation/files", Command: []string{"admin", "docs", "files"}, Args: []string(nil), Controller: "DocumentationController"},
	{Feature: "documentation", Method: "GET", Endpoint: "/api/admin/documentation/content", Command: []string{"admin", "docs", "get"}, Args: []string(nil), Controller: "DocumentationController"},
	{Feature: "documentation", Method: "POST", Endpoint: "/api/admin/documentation/publish", Command: []string{"admin", "docs", "publish"}, Args: []string(nil), Controller: "DocumentationController"},
	{Feature: "documentation", Method: "GET", Endpoint: "/api/admin/documentation/publish/logs", Command: []string{"admin", "docs", "publish-logs"}, Args: []string(nil), Controller: "DocumentationController"},
	{Feature: "documentation", Method: "PUT", Endpoint: "/api/admin/documentation/content", Command: []string{"admin", "docs", "update"}, Args: []string(nil), Controller: "DocumentationController"},
}
