// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package alerts

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "alerts", Method: "POST", Endpoint: "/api/v1/alerts/channels", Command: []string{"alert", "channel", "create"}, Args: []string(nil), Controller: "AlertController"},
	{Feature: "alerts", Method: "DELETE", Endpoint: "/api/v1/alerts/channels/{channelId}", Command: []string{"alert", "channel", "delete"}, Args: []string{"channel-id"}, Controller: "AlertController"},
	{Feature: "alerts", Method: "GET", Endpoint: "/api/v1/alerts/channels", Command: []string{"alert", "channel", "list"}, Args: []string(nil), Controller: "AlertController"},
	{Feature: "alerts", Method: "PUT", Endpoint: "/api/v1/alerts/channels/{channelId}", Command: []string{"alert", "channel", "update"}, Args: []string{"channel-id"}, Controller: "AlertController"},
	{Feature: "alerts", Method: "GET", Endpoint: "/api/v1/alerts/projects/{projectId}/config", Command: []string{"alert", "project-config", "get"}, Args: []string{"project-id"}, Controller: "AlertController"},
	{Feature: "alerts", Method: "GET", Endpoint: "/api/v1/alerts/projects/configs", Command: []string{"alert", "project-config", "list"}, Args: []string(nil), Controller: "AlertController"},
	{Feature: "alerts", Method: "PUT", Endpoint: "/api/v1/alerts/projects/{projectId}/config", Command: []string{"alert", "project-config", "set"}, Args: []string{"project-id"}, Controller: "AlertController"},
	{Feature: "alerts", Method: "GET", Endpoint: "/api/v1/alerts/user-config", Command: []string{"alert", "user-config", "get"}, Args: []string(nil), Controller: "AlertController"},
	{Feature: "alerts", Method: "PUT", Endpoint: "/api/v1/alerts/user-config", Command: []string{"alert", "user-config", "set"}, Args: []string(nil), Controller: "AlertController"},
}
