// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package dbcluster

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "dbcluster", Method: "PATCH", Endpoint: "/api/namespaces/{namespace}/cluster-deployments/{releaseName}/backup", Command: []string{"cluster", "backup", "settings", "set"}, Args: []string{"release-name"}, Controller: "ClusterDeploymentController"},
	{Feature: "dbcluster", Method: "PATCH", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/backup", Command: []string{"cluster", "backup", "settings", "set"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/certificate", Command: []string{"cluster", "certificate"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "POST", Endpoint: "/api/namespaces/{namespace}/clusters/clone-from-backup", Command: []string{"cluster", "clone-from-backup"}, Args: []string(nil), Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/credentials", Command: []string{"cluster", "console", "credentials"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/data", Command: []string{"cluster", "console", "data"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/deployment", Command: []string{"cluster", "console", "deployment"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/namespaces", Command: []string{"cluster", "console", "namespaces"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/objects", Command: []string{"cluster", "console", "objects"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "POST", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/query", Command: []string{"cluster", "console", "query"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "POST", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/console/test", Command: []string{"cluster", "console", "test"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "DELETE", Endpoint: "/api/namespaces/{namespace}/clusters/{id}", Command: []string{"cluster", "delete"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "POST", Endpoint: "/api/namespaces/{namespace}/cluster-deployments", Command: []string{"cluster", "deploy"}, Args: []string(nil), Controller: "ClusterDeploymentController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/cluster-deployments/{releaseName}/values", Command: []string{"cluster", "deployment", "values"}, Args: []string{"release-name"}, Controller: "ClusterDeploymentController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}", Command: []string{"cluster", "get"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/deployments", Command: []string{"cluster", "history"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters", Command: []string{"cluster", "list"}, Args: []string(nil), Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/metrics", Command: []string{"cluster", "metrics"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "PATCH", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/settings", Command: []string{"cluster", "settings", "update"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/cluster-deployments/{releaseName}", Command: []string{"cluster", "status"}, Args: []string{"release-name"}, Controller: "ClusterDeploymentController"},
	{Feature: "dbcluster", Method: "PATCH", Endpoint: "/api/namespaces/{namespace}/clusters/{id}", Command: []string{"cluster", "update"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "POST", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/upgrade-version", Command: []string{"cluster", "upgrade"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/namespaces/{namespace}/clusters/{id}/values", Command: []string{"cluster", "values"}, Args: []string{"cluster-id"}, Controller: "ClusterController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/releases/{releaseName}/deployment-stream", Command: []string{"cluster", "watch"}, Args: []string{"release-name"}, Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/database-resources", Command: []string{"kubernetes", "database-resources"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/events", Command: []string{"kubernetes", "events"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/overview", Command: []string{"kubernetes", "overview"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/pods", Command: []string{"kubernetes", "pods"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/persistent-volume-claims", Command: []string{"kubernetes", "pvc"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/services", Command: []string{"kubernetes", "services"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/test", Command: []string{"kubernetes", "test"}, Args: []string(nil), Controller: "KubernetesController"},
	{Feature: "dbcluster", Method: "GET", Endpoint: "/api/kubernetes/namespaces/{namespace}/pods/{podName}/logs/stream", Command: []string{"logs"}, Args: []string{"pod-name"}, Controller: "KubernetesController"},
}
