// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package sonarqube

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "sonarqube", Method: "POST", Endpoint: "/api/v1/projects/{projectId}/sonarqube/access", Command: []string{"sonarqube", "access"}, Args: []string{"project-id"}, Controller: "SonarQubeProjectController"},
	{Feature: "sonarqube", Method: "GET", Endpoint: "/api/v1/projects/{projectId}/sonarqube", Command: []string{"sonarqube", "summary"}, Args: []string{"project-id"}, Controller: "SonarQubeProjectController"},
}
