// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package databasebackup

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "databasebackup", Method: "DELETE", Endpoint: "/api/backups/{targetType}/{id}/{runId}", Command: []string{"backup", "delete"}, Args: []string{"type", "id", "run-id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "GET", Endpoint: "/api/backups/download/{targetType}/{id}/{runId}", Command: []string{"backup", "download"}, Args: []string{"type", "id", "run-id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/backups/restore/{targetType}/{id}/{runId}", Command: []string{"backup", "restore"}, Args: []string{"type", "id", "run-id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/backups/restore/{targetType}/{id}/{runId}/cancel", Command: []string{"backup", "restore", "cancel"}, Args: []string{"type", "id", "run-id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "GET", Endpoint: "/api/backups/settings/{targetType}/{id}", Command: []string{"backup", "settings", "get"}, Args: []string{"type", "id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/backups/settings/{targetType}/{id}", Command: []string{"backup", "settings", "set"}, Args: []string{"type", "id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/backups/trigger/{targetType}/{id}", Command: []string{"backup", "trigger"}, Args: []string{"type", "id"}, Controller: "UnifiedBackupController"},
	{Feature: "databasebackup", Method: "DELETE", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup/runs/{runId}", Command: []string{"database", "backup", "delete"}, Args: []string{"deployment-id", "run-id"}, Controller: "DatabaseDeploymentBackupController"},
	{Feature: "databasebackup", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup/runs/{runId}/download", Command: []string{"database", "backup", "download"}, Args: []string{"deployment-id", "run-id"}, Controller: "DatabaseDeploymentBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup/runs/{runId}/restore", Command: []string{"database", "backup", "restore"}, Args: []string{"deployment-id", "run-id"}, Controller: "DatabaseDeploymentBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup/runs/{runId}/restore/cancel", Command: []string{"database", "backup", "restore", "cancel"}, Args: []string{"deployment-id", "run-id"}, Controller: "DatabaseDeploymentBackupController"},
	{Feature: "databasebackup", Method: "POST", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup/run", Command: []string{"database", "backup", "run"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentBackupController"},
	{Feature: "databasebackup", Method: "GET", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup", Command: []string{"database", "backup", "settings", "get"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentBackupController"},
	{Feature: "databasebackup", Method: "PATCH", Endpoint: "/api/v1/database-deployments/{deploymentId}/backup", Command: []string{"database", "backup", "settings", "set"}, Args: []string{"deployment-id"}, Controller: "DatabaseDeploymentBackupController"},
}
