// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package imagescanner

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "imagescanner", Method: "GET", Endpoint: "/api/v1/image-scanner/scans/{scanId}", Command: []string{"scan", "get"}, Args: []string{"scan-id"}, Controller: "ImageScannerController"},
	{Feature: "imagescanner", Method: "GET", Endpoint: "/api/v1/image-scanner/images", Command: []string{"scan", "images"}, Args: []string(nil), Controller: "ImageScannerController"},
	{Feature: "imagescanner", Method: "GET", Endpoint: "/api/v1/image-scanner/scans", Command: []string{"scan", "list"}, Args: []string(nil), Controller: "ImageScannerController"},
	{Feature: "imagescanner", Method: "GET", Endpoint: "/api/v1/image-scanner/scans/{scanId}/report", Command: []string{"scan", "report"}, Args: []string{"scan-id"}, Controller: "ImageScannerController"},
	{Feature: "imagescanner", Method: "POST", Endpoint: "/api/v1/image-scanner/scans", Command: []string{"scan", "start"}, Args: []string(nil), Controller: "ImageScannerController"},
}
