// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package workspaces

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "workspaces", Method: "POST", Endpoint: "/api/v1/workspaces/bootstrap", Command: []string{"workspace", "bootstrap"}, Args: []string(nil), Controller: "WorkspaceController"},
	{Feature: "workspaces", Method: "GET", Endpoint: "/api/v1/workspaces/quota-requests/payment-status", Command: []string{"workspace", "quota", "payment-status"}, Args: []string{"md5"}, Controller: "WorkspaceController"},
	{Feature: "workspaces", Method: "GET", Endpoint: "/api/v1/workspaces/quota-pricing", Command: []string{"workspace", "quota", "pricing"}, Args: []string(nil), Controller: "WorkspaceController"},
	{Feature: "workspaces", Method: "POST", Endpoint: "/api/v1/workspaces/quota-requests", Command: []string{"workspace", "quota", "request"}, Args: []string(nil), Controller: "WorkspaceController"},
	{Feature: "workspaces", Method: "GET", Endpoint: "/api/v1/workspaces/bootstrap", Command: []string{"workspace", "status"}, Args: []string(nil), Controller: "WorkspaceController"},
}
