// Code generated by scripts/generate-route-registry; DO NOT EDIT.

package gitintegration

import "github.com/yourname/a8s/internal/cli/catalog"

var Routes = []catalog.Route{
	{Feature: "gitintegration", Method: "GET", Endpoint: "/api/v1/git-integrations/{provider}/brokered-account", Command: []string{"git", "account"}, Args: []string{"provider"}, Controller: "GitIntegrationController"},
	{Feature: "gitintegration", Method: "POST", Endpoint: "/api/v1/git-integrations/{provider}/connect", Command: []string{"git", "connect"}, Args: []string{"provider"}, Controller: "GitIntegrationController"},
	{Feature: "gitintegration", Method: "DELETE", Endpoint: "/api/v1/git-integrations/{provider}", Command: []string{"git", "disconnect"}, Args: []string{"provider"}, Controller: "GitIntegrationController"},
	{Feature: "gitintegration", Method: "GET", Endpoint: "/api/v1/git-integrations/linked-providers", Command: []string{"git", "providers"}, Args: []string(nil), Controller: "GitIntegrationController"},
	{Feature: "gitintegration", Method: "GET", Endpoint: "/api/v1/git-integrations/{provider}/repos", Command: []string{"git", "repos"}, Args: []string{"provider"}, Controller: "GitIntegrationController"},
	{Feature: "gitintegration", Method: "GET", Endpoint: "/api/v1/git-integrations/{provider}/state", Command: []string{"git", "state"}, Args: []string{"provider"}, Controller: "GitIntegrationController"},
	{Feature: "gitintegration", Method: "POST", Endpoint: "/api/v1/git-integrations/{provider}/sync-keycloak-token", Command: []string{"git", "sync-token"}, Args: []string{"provider"}, Controller: "GitIntegrationController"},
}
